from __future__ import annotations

import argparse
import itertools
import json
import os
from dataclasses import dataclass
from typing import List, Tuple, Optional

import numpy as np
import pandas as pd

from figure_audit import trajectory_history_from_arrays, write_json_manifest

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor

try:
    from scipy.stats import qmc
except Exception:  # pragma: no cover
    qmc = None

try:
    from numba import njit

    _HAS_NUMBA = True
except ImportError:  # pragma: no cover
    _HAS_NUMBA = False

    def njit(*args, **kwargs):  # type: ignore[misc]
        if args and callable(args[0]):
            return args[0]

        def _decorator(func):
            return func

        return _decorator


N_STRAINS = 5

# OD600 -> CFU/mL calibration (experimental growth curves; used for provenance / unit conversion).
ECOLI_OD_TO_CFU_SLOPE = 3.14e8
ECOLI_OD_TO_CFU_INTERCEPT = -4.81e7
ECOLI_OD_TO_CFU_R2 = 0.8460

LLACTIS_OD_TO_CFU_SLOPE = 2.89e8
LLACTIS_OD_TO_CFU_INTERCEPT = 2.56e7
LLACTIS_OD_TO_CFU_R2 = 0.8673

PROFILE_ALIASES = ("paper_figure", "manuscript_strict", "experimental_calibrated")
DEFAULT_ODE_PROFILE_NAME = "paper_figure"

NUMBA_SIMULATION_ENABLED = _HAS_NUMBA and os.environ.get("SIM_DISABLE_NUMBA", "").lower() not in {
    "1",
    "true",
    "yes",
}

BIO_COLS = (
    [f"B0_{i}" for i in range(1, 6)]
    + [f"k_{i}" for i in range(1, 6)]
    + [f"g_{i}" for i in range(1, 6)]
    + [f"rho_{i}" for i in range(1, 6)]
    + [f"mu_{i}" for i in range(1, 6)]
)
KPI_COLS = ["P_AUC"] + [f"LR{i}" for i in range(1, 6)]
# Keep the original CSV order for compatibility with the uploaded notebook/code.
TARGET_COLS = ["u_max"] + [f"Tthr_{i}" for i in range(1, 6)]
ALL_COLS = BIO_COLS + TARGET_COLS + KPI_COLS


def save_representative_artifacts(res: "SimulationResult", profile: "ModelProfile", outdir: str) -> None:
    """Write CSV + manifest only; PNG is generated by figure_audit.py."""
    history_df = trajectory_history_from_arrays(res.times, res.C, res.P_total, res.B_total)
    history_path = os.path.join(outdir, "representative_trajectory_history.csv")
    history_df.to_csv(history_path, index=False)

    metrics_path = os.path.join(outdir, f"representative_metrics_{profile.name}.csv")
    metrics_dataframe("representative", res).to_csv(metrics_path, index=False)

    figure_png = f"representative_{profile.name}.png"
    manifest = {
        "mode": "representative",
        "profile": profile.name,
        "probiotic_two_compartment": profile.probiotic_model == "two_compartment",
        "total_dosage": float(res.total_dosage),
        "P_AUC": float(res.P_AUC),
        "dose_count": int(res.dose_count),
        "u_max": float(res.u_max),
        "dose_times_h": [float(t) for t in res.dose_times],
        "T_thr": [float(v) for v in res.T_thr],
        "trajectory_history_csv": "representative_trajectory_history.csv",
        "metrics_csv": os.path.basename(metrics_path),
        "figure_png": figure_png,
        "figures_note": f"Run: python figure_audit.py --mode generate_plots --groups ode --ode_outdir {outdir}",
    }
    manifest.update(profile_provenance(profile))
    write_json_manifest(outdir, "ode_simulation_manifest.json", manifest)
    print(f"Saved {history_path}")
    print(f"Saved {metrics_path}")
    print(f"Saved ode_simulation_manifest.json")
    print(f"Generate figure: python figure_audit.py --mode generate_plots --groups ode --ode_outdir {outdir}")


def save_train_compare_trajectory_artifact(res: "SimulationResult", outdir: str, label: str = "closed_loop_srl") -> None:
    history_name = f"{label}_trajectory_history.csv"
    history_path = os.path.join(outdir, history_name)
    trajectory_history_from_arrays(res.times, res.C, res.P_total, res.B_total).to_csv(history_path, index=False)
    figure_png = "Fig_reviewer_closed_loop_comparison.png"
    manifest_path = os.path.join(outdir, "ode_simulation_manifest.json")
    manifest: dict = {}
    if os.path.exists(manifest_path):
        with open(manifest_path, encoding="utf-8") as fh:
            manifest = json.load(fh)
    manifest.update(
        {
            "mode": "train_compare",
            "train_compare_label": label,
            "probiotic_two_compartment": True,
            "total_dosage": float(res.total_dosage),
            "P_AUC": float(res.P_AUC),
            "T_thr": [float(v) for v in res.T_thr],
            "trajectory_history_csv": history_name,
            "figure_png": figure_png,
            "figures_note": f"Run: python figure_audit.py --mode generate_plots --groups ode --ode_outdir {outdir}",
        }
    )
    write_json_manifest(outdir, "ode_simulation_manifest.json", manifest)
    print(f"Saved {history_path}")
    print(f"Generate figure: python figure_audit.py --mode generate_plots --groups ode --ode_outdir {outdir}")


@dataclass(frozen=True)
class ModelProfile:
    name: str
    # pathogen constants/defaults
    K_pathogen: np.ndarray
    k_rep: np.ndarray
    B0_rep: np.ndarray
    mu_rep: np.ndarray
    gamma_s_rep: np.ndarray
    rho_rep: np.ndarray
    eta_pathogen: np.ndarray
    alpha: np.ndarray
    beta: np.ndarray
    # probiotic constants
    probiotic_model: str  # 'two_compartment' or 'single'
    K_P: float
    k_P: float
    gamma_P: float
    rho_P: float
    eta_P: float
    mu_P: float
    P0: float
    # AMP/control/numerics
    lambda_amp: float
    u_max_rep: float
    T_thr_rep: np.ndarray
    dt_detect: float
    t_end: float
    dt: float


def _alpha_matrix() -> np.ndarray:
    a = np.full((N_STRAINS, N_STRAINS), 0.05, dtype=float)
    np.fill_diagonal(a, 1.0)
    return a


def od_to_cfu_ecoli(od600: float | np.ndarray) -> float | np.ndarray:
    """Convert E. coli OD600 to CFU/mL (R2 = 0.8460)."""
    return ECOLI_OD_TO_CFU_SLOPE * od600 + ECOLI_OD_TO_CFU_INTERCEPT


def od_to_cfu_llactis(od600: float | np.ndarray) -> float | np.ndarray:
    """Convert L. lactis OD600 to CFU/mL (R2 = 0.8673)."""
    return LLACTIS_OD_TO_CFU_SLOPE * od600 + LLACTIS_OD_TO_CFU_INTERCEPT


def experimental_calibrated_provenance() -> dict:
    """Parameter source notes for the experimental_calibrated profile."""
    return {
        "k_pathogen_source": "E. coli CFU logistic mean k = 0.241 h^-1",
        "K_pathogen_source": "E. coli CFU stationary phase / manuscript reported ~1.5e9 CFU/mL",
        "k_P_source": "L. lactis CFU logistic k = 0.2522 h^-1",
        "K_P_source": "L. lactis OD-to-CFU converted YM average ≈ 3.35e8 CFU/mL",
        "gamma_P_source": "preliminary AMP growth-rate suppression estimate ≈ 0.0015",
        "non_identifiable_parameters": ["rho", "mu", "eta", "alpha", "beta", "lambda_amp"],
        "assumption_parameters": ["rho", "mu", "eta", "alpha", "beta", "lambda_amp"],
        "od_to_cfu_calibration": {
            "E_coli": {
                "formula": "CFU = 3.14e8 * OD600 - 4.81e7",
                "R2": ECOLI_OD_TO_CFU_R2,
            },
            "L_lactis": {
                "formula": "CFU = 2.89e8 * OD600 + 2.56e7",
                "R2": LLACTIS_OD_TO_CFU_R2,
            },
        },
        "parameter_provenance_note": (
            "Only k_pathogen, K_pathogen, k_P, K_P, and gamma_P are tied to experimental "
            "growth-curve calibration. rho, mu, eta, alpha, beta, and lambda_amp remain "
            "assumptions / sensitivity parameters and were not fitted from growth curves."
        ),
    }


def profile_provenance(profile: ModelProfile) -> dict:
    if profile.name == DEFAULT_ODE_PROFILE_NAME:
        return experimental_calibrated_provenance()
    return {}


def _default_ode_profile() -> ModelProfile:
    """Default ODE parameter set (paper_figure profile)."""
    return ModelProfile(
        name=DEFAULT_ODE_PROFILE_NAME,
        K_pathogen=np.array([1.60e8, 1.75e8, 1.70e8, 1.65e8, 1.80e8], dtype=float),
        k_rep=np.array([1.09, 0.91, 1.15, 0.97, 1.03], dtype=float),
        B0_rep=np.array([2.60e6, 2.90e6, 2.80e6, 2.70e6, 3.00e6], dtype=float),
        mu_rep=np.array([1.50e-7, 1.70e-7, 1.40e-7, 1.80e-7, 1.60e-7], dtype=float),
        gamma_s_rep=np.array([0.035, 0.032, 0.038, 0.030, 0.036], dtype=float),
        rho_rep=np.array([0.54, 0.58, 0.50, 0.56, 0.52], dtype=float),
        eta_pathogen=np.array([0.96, 0.93, 0.98, 0.90, 0.95], dtype=float),
        alpha=_alpha_matrix(),
        beta=np.full(N_STRAINS, 0.10, dtype=float),
        probiotic_model="two_compartment",
        K_P=1.50e8,
        k_P=0.80,
        gamma_P=0.018,
        rho_P=0.40,
        eta_P=0.95,
        mu_P=1.0e-7,
        P0=1.0e6,
        lambda_amp=0.50,
        u_max_rep=18.0,
        T_thr_rep=0.5 * np.array([4.000e7, 3.975e7, 3.950e7, 3.925e7, 3.900e7], dtype=float),
        dt_detect=1.0 / 6.0,
        t_end=96.0,
        dt=0.4,
    )


def get_profile(name: str) -> ModelProfile:
    """Return the default calibrated ODE profile (legacy names are aliases)."""
    name = name.lower()
    if name in PROFILE_ALIASES:
        return _default_ode_profile()
    raise ValueError(f"profile must be one of {PROFILE_ALIASES}.")


@dataclass
class SimulationResult:
    profile_name: str
    times: np.ndarray
    B_total: np.ndarray
    B_S: np.ndarray
    B_T: np.ndarray
    P_total: np.ndarray
    P_S: Optional[np.ndarray]
    P_T: Optional[np.ndarray]
    C: np.ndarray
    dose_times: List[float]
    dose_count: int
    total_dosage: float
    P_AUC: float
    LR: np.ndarray
    u_max: float
    T_thr: np.ndarray


def _competition_term(alpha: np.ndarray, beta: np.ndarray, B_S: np.ndarray, B_T: np.ndarray, P_tot: float) -> np.ndarray:
    BT = B_S + B_T
    comp = alpha @ BT
    comp = comp + beta * P_tot
    return comp


def _simulate_forward_euler_core(
    B0: np.ndarray,
    k_arr: np.ndarray,
    gamma_arr: np.ndarray,
    gamma_T: np.ndarray,
    mu_arr: np.ndarray,
    u_max: float,
    T_thr: np.ndarray,
    K_pathogen: np.ndarray,
    eta_pathogen: np.ndarray,
    alpha: np.ndarray,
    beta: np.ndarray,
    two_compartment: bool,
    K_P: float,
    k_P: float,
    gamma_P: float,
    rho_P: float,
    eta_P: float,
    mu_P: float,
    P0: float,
    lambda_amp: float,
    dt_detect: float,
    t_end: float,
    dt: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, int, int]:
    """Pure-Python forward Euler integrator (fallback when Numba is unavailable)."""
    steps = int(round(t_end / dt)) + 1
    if steps < 2:
        steps = 2
    dt_sim = t_end / float(steps - 1)

    B_S = B0.copy()
    B_T = np.zeros(N_STRAINS, dtype=float)
    P_S = float(P0)
    P_T = 0.0
    P = float(P0)
    C = 0.0

    B_S_hist = np.zeros((steps, N_STRAINS), dtype=float)
    B_T_hist = np.zeros((steps, N_STRAINS), dtype=float)
    P_hist = np.zeros(steps, dtype=float)
    P_S_hist = np.zeros(steps, dtype=float)
    P_T_hist = np.zeros(steps, dtype=float)
    C_hist = np.zeros(steps, dtype=float)
    dose_times_buf = np.full(steps, np.nan, dtype=float)

    next_detect = 0.0
    dose_count = 0

    for idx in range(steps):
        t = idx * dt_sim
        B_S_hist[idx] = B_S
        B_T_hist[idx] = B_T
        if two_compartment:
            P_hist[idx] = P_S + P_T
            P_S_hist[idx] = P_S
            P_T_hist[idx] = P_T
        else:
            P_hist[idx] = P
        C_hist[idx] = C

        if t >= next_detect - 1e-12:
            if np.any(B_S + B_T > T_thr):
                C += u_max
                dose_count += 1
                dose_times_buf[dose_count - 1] = t
            next_detect += dt_detect

        P_tot = P_S + P_T if two_compartment else P
        comp = _competition_term(alpha, beta, B_S, B_T, P_tot)
        logistic_factor = 1.0 - comp / K_pathogen
        dB_S = k_arr * B_S * logistic_factor - gamma_arr * C * B_S - mu_arr * B_S
        dB_T = eta_pathogen * k_arr * B_T * logistic_factor - gamma_T * C * B_T + mu_arr * B_S
        dC = -lambda_amp * C

        B_S = np.clip(B_S + dB_S * dt_sim, 0.0, None)
        B_T = np.clip(B_T + dB_T * dt_sim, 0.0, None)

        if two_compartment:
            gamma_P_T = gamma_P * (1.0 - rho_P)
            P_tot = P_S + P_T
            dP_S = k_P * P_S * (1.0 - P_tot / K_P) - gamma_P * C * P_S - mu_P * P_S
            dP_T = eta_P * k_P * P_T * (1.0 - P_tot / K_P) - gamma_P_T * C * P_T + mu_P * P_S
            P_S = max(P_S + dP_S * dt_sim, 0.0)
            P_T = max(P_T + dP_T * dt_sim, 0.0)
        else:
            dP = k_P * P * (1.0 - P / K_P) - gamma_P * C * P
            P = max(P + dP * dt_sim, 0.0)

        C = max(C + dC * dt_sim, 0.0)

    return B_S_hist, B_T_hist, P_hist, P_S_hist, P_T_hist, C_hist, dose_times_buf, dose_count, steps


@njit(cache=True, fastmath=True)
def _simulate_forward_euler_numba(
    B0: np.ndarray,
    k_arr: np.ndarray,
    gamma_arr: np.ndarray,
    gamma_T: np.ndarray,
    mu_arr: np.ndarray,
    u_max: float,
    T_thr: np.ndarray,
    K_pathogen: np.ndarray,
    eta_pathogen: np.ndarray,
    alpha: np.ndarray,
    beta: np.ndarray,
    two_compartment: bool,
    K_P: float,
    k_P: float,
    gamma_P: float,
    rho_P: float,
    eta_P: float,
    mu_P: float,
    P0: float,
    lambda_amp: float,
    dt_detect: float,
    t_end: float,
    dt: float,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, int, int]:
    steps = int(round(t_end / dt)) + 1
    if steps < 2:
        steps = 2
    dt_sim = t_end / float(steps - 1)

    B_S = B0.copy()
    B_T = np.zeros(N_STRAINS)
    P_S = P0
    P_T = 0.0
    P = P0
    C = 0.0

    B_S_hist = np.zeros((steps, N_STRAINS))
    B_T_hist = np.zeros((steps, N_STRAINS))
    P_hist = np.zeros(steps)
    P_S_hist = np.zeros(steps)
    P_T_hist = np.zeros(steps)
    C_hist = np.zeros(steps)
    dose_times_buf = np.full(steps, np.nan)

    next_detect = 0.0
    dose_count = 0

    for idx in range(steps):
        t = idx * dt_sim
        for i in range(N_STRAINS):
            B_S_hist[idx, i] = B_S[i]
            B_T_hist[idx, i] = B_T[i]

        if two_compartment:
            P_hist[idx] = P_S + P_T
            P_S_hist[idx] = P_S
            P_T_hist[idx] = P_T
            P_tot = P_S + P_T
        else:
            P_hist[idx] = P
            P_tot = P
        C_hist[idx] = C

        if t >= next_detect - 1.0e-12:
            trigger = False
            for i in range(N_STRAINS):
                if B_S[i] + B_T[i] > T_thr[i]:
                    trigger = True
                    break
            if trigger:
                C += u_max
                dose_times_buf[dose_count] = t
                dose_count += 1
            next_detect += dt_detect

        comp = np.empty(N_STRAINS)
        BT = B_S + B_T
        for i in range(N_STRAINS):
            s = 0.0
            for j in range(N_STRAINS):
                s += alpha[i, j] * BT[j]
            comp[i] = s + beta[i] * P_tot

        for i in range(N_STRAINS):
            logistic_factor = 1.0 - comp[i] / K_pathogen[i]
            dB_S_i = k_arr[i] * B_S[i] * logistic_factor - gamma_arr[i] * C * B_S[i] - mu_arr[i] * B_S[i]
            dB_T_i = eta_pathogen[i] * k_arr[i] * B_T[i] * logistic_factor - gamma_T[i] * C * B_T[i] + mu_arr[i] * B_S[i]
            B_S[i] = max(B_S[i] + dB_S_i * dt_sim, 0.0)
            B_T[i] = max(B_T[i] + dB_T_i * dt_sim, 0.0)

        dC = -lambda_amp * C

        if two_compartment:
            gamma_P_T = gamma_P * (1.0 - rho_P)
            P_tot = P_S + P_T
            dP_S = k_P * P_S * (1.0 - P_tot / K_P) - gamma_P * C * P_S - mu_P * P_S
            dP_T = eta_P * k_P * P_T * (1.0 - P_tot / K_P) - gamma_P_T * C * P_T + mu_P * P_S
            P_S_new = P_S + dP_S * dt_sim
            P_T_new = P_T + dP_T * dt_sim
            if P_S_new < 0.0:
                P_S_new = 0.0
            if P_T_new < 0.0:
                P_T_new = 0.0
            P_S = P_S_new
            P_T = P_T_new
        else:
            dP = k_P * P * (1.0 - P / K_P) - gamma_P * C * P
            P_new = P + dP * dt_sim
            if P_new < 0.0:
                P_new = 0.0
            P = P_new

        C_new = C + dC * dt_sim
        if C_new < 0.0:
            C_new = 0.0
        C = C_new

    return B_S_hist, B_T_hist, P_hist, P_S_hist, P_T_hist, C_hist, dose_times_buf, dose_count, steps


def _run_forward_euler(
    B0: np.ndarray,
    k_arr: np.ndarray,
    gamma_arr: np.ndarray,
    gamma_T: np.ndarray,
    mu_arr: np.ndarray,
    u_max: float,
    T_thr: np.ndarray,
    profile: ModelProfile,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, List[float], int, np.ndarray]:
    two_compartment = profile.probiotic_model == "two_compartment"
    euler_fn = _simulate_forward_euler_numba if NUMBA_SIMULATION_ENABLED else _simulate_forward_euler_core
    (
        B_S_hist,
        B_T_hist,
        P_hist,
        P_S_hist,
        P_T_hist,
        C_hist,
        dose_times_buf,
        dose_count,
        steps,
    ) = euler_fn(
        B0,
        k_arr,
        gamma_arr,
        gamma_T,
        mu_arr,
        u_max,
        T_thr,
        profile.K_pathogen,
        profile.eta_pathogen,
        profile.alpha,
        profile.beta,
        two_compartment,
        profile.K_P,
        profile.k_P,
        profile.gamma_P,
        profile.rho_P,
        profile.eta_P,
        profile.mu_P,
        profile.P0,
        profile.lambda_amp,
        profile.dt_detect,
        profile.t_end,
        profile.dt,
    )
    times = np.linspace(0.0, profile.t_end, steps)
    dose_times = [float(v) for v in dose_times_buf[:dose_count]]
    P_S_out = P_S_hist if two_compartment else None
    P_T_out = P_T_hist if two_compartment else None
    return B_S_hist, B_T_hist, P_hist, P_S_out, P_T_out, C_hist, dose_times, dose_count, times


def simulate_case(
    profile: ModelProfile,
    B0: Optional[np.ndarray] = None,
    k_arr: Optional[np.ndarray] = None,
    gamma_arr: Optional[np.ndarray] = None,
    rho_arr: Optional[np.ndarray] = None,
    mu_arr: Optional[np.ndarray] = None,
    u_max: Optional[float] = None,
    T_thr: Optional[np.ndarray] = None,
    return_history: bool = True,
) -> SimulationResult:
    """Forward Euler simulation of the five-pathogen threshold-triggered AMP system."""
    B0 = np.asarray(profile.B0_rep if B0 is None else B0, dtype=float)
    k_arr = np.asarray(profile.k_rep if k_arr is None else k_arr, dtype=float)
    gamma_arr = np.asarray(profile.gamma_s_rep if gamma_arr is None else gamma_arr, dtype=float)
    rho_arr = np.asarray(profile.rho_rep if rho_arr is None else rho_arr, dtype=float)
    mu_arr = np.asarray(profile.mu_rep if mu_arr is None else mu_arr, dtype=float)
    T_thr = np.asarray(profile.T_thr_rep if T_thr is None else T_thr, dtype=float)
    u_max = float(profile.u_max_rep if u_max is None else u_max)

    if not (len(B0) == len(k_arr) == len(gamma_arr) == len(rho_arr) == len(mu_arr) == len(T_thr) == N_STRAINS):
        raise ValueError("B0, k_arr, gamma_arr, rho_arr, mu_arr, and T_thr must all have length 5.")
    if np.any(T_thr <= 0) or u_max < 0:
        raise ValueError("Thresholds must be positive and u_max must be non-negative.")

    # gamma_T = gamma_S * (1-rho); default rho=0.5 gives gamma_T = 0.5 gamma_S.
    gamma_T = gamma_arr * (1.0 - rho_arr)

    (
        B_S_hist,
        B_T_hist,
        P_hist,
        P_S_hist,
        P_T_hist,
        C_hist,
        dose_times,
        dose_count,
        times,
    ) = _run_forward_euler(B0, k_arr, gamma_arr, gamma_T, mu_arr, u_max, T_thr, profile)

    B_total = B_S_hist + B_T_hist
    P_AUC = float(np.trapezoid(P_hist / profile.K_P, times) / profile.t_end)
    LR = np.log10(B0 / np.clip(B_total[-1], 1.0, None))

    return SimulationResult(
        profile_name=profile.name,
        times=times,
        B_total=B_total,
        B_S=B_S_hist,
        B_T=B_T_hist,
        P_total=P_hist,
        P_S=P_S_hist,
        P_T=P_T_hist,
        C=C_hist,
        dose_times=dose_times,
        dose_count=dose_count,
        total_dosage=float(dose_count * u_max),
        P_AUC=P_AUC,
        LR=LR,
        u_max=u_max,
        T_thr=T_thr,
    )


def metrics_dataframe(label: str, res: SimulationResult) -> pd.DataFrame:
    row = {
        "controller": label,
        "profile": res.profile_name,
        "u_max": res.u_max,
        "dose_count": res.dose_count,
        "total_dosage_ug_per_mL": res.total_dosage,
        "P_AUC": res.P_AUC,
        "final_total_pathogen_CFU_per_mL": float(res.B_total[-1].sum()),
        "final_probiotic_CFU_per_mL": float(res.P_total[-1]),
    }
    for i, thr in enumerate(res.T_thr, start=1):
        row[f"Tthr_{i}"] = float(thr)
    for i, lr in enumerate(res.LR, start=1):
        row[f"LR{i}"] = float(lr)
    return pd.DataFrame([row])


def _row_from_profile_case(profile: ModelProfile, B0, k_arr, gamma_arr, rho_arr, mu_arr, u_max, T_thr) -> np.ndarray:
    res = simulate_case(profile, B0, k_arr, gamma_arr, rho_arr, mu_arr, u_max, T_thr, return_history=False)
    return np.concatenate([B0, k_arr, gamma_arr, rho_arr, mu_arr, [u_max], T_thr, [res.P_AUC], res.LR])


def generate_rows(profile: ModelProfile, n_bio: int = 500) -> pd.DataFrame:
    """Generate 220,000 rows when n_bio=500 under the original code-aligned grid."""
    if qmc is None:
        raise ImportError("scipy is required: pip install scipy")

    sampler = qmc.LatinHypercube(d=15, seed=0)
    lhs_mat = sampler.random(n=n_bio)

    def scale(v, lo, hi):
        return lo + v * (hi - lo)

    B0_lo, B0_hi = 0.6 * profile.B0_rep, 1.4 * profile.B0_rep
    k_lo, k_hi = 0.8 * profile.k_rep, 1.2 * profile.k_rep
    g_lo, g_hi = 0.8 * profile.gamma_s_rep, 1.2 * profile.gamma_s_rep
    rho_add_values = [0.0, 0.05]
    u_grid = np.arange(10.0, 31.0, 2.0)
    thr_levels = 0.4 * 2.0e7 * 1.26 ** np.arange(10)

    bio_vecs = []
    for row in lhs_mat:
        ptr = 0
        B0 = scale(row[ptr:ptr + 5], B0_lo, B0_hi); ptr += 5
        k_v = scale(row[ptr:ptr + 5], k_lo, k_hi); ptr += 5
        g_v = scale(row[ptr:ptr + 5], g_lo, g_hi); ptr += 5
        bio_vecs.append((B0, k_v, g_v))

    sob = qmc.Sobol(d=5, scramble=True, seed=42)
    T_unit = sob.random_base2(m=4)[:10]
    T_vecs = thr_levels[(T_unit * 10).astype(int)]

    rows = []
    mu_designs = [0.8 * profile.mu_rep, 1.2 * profile.mu_rep]
    total = len(bio_vecs) * len(mu_designs) * len(rho_add_values) * len(u_grid) * len(T_vecs)

    done = 0
    for B0, k_v, g_v in bio_vecs:
        for mu_v, radd in itertools.product(mu_designs, rho_add_values):
            rho_v = np.clip(profile.rho_rep + radd, 0.0, 0.95)
            for u in u_grid:
                for T in T_vecs:
                    rows.append(_row_from_profile_case(profile, B0, k_v, g_v, rho_v, mu_v, float(u), T))
                    done += 1
                    if done % 10000 == 0:
                        print(f"generated {done:,}/{total:,} rows")

    return pd.DataFrame(rows, columns=ALL_COLS)


def write_feature_target_csv(df: pd.DataFrame, outdir: str) -> None:
    df[BIO_COLS + KPI_COLS].to_csv(os.path.join(outdir, "X_features.csv"), index=False)
    df[TARGET_COLS].to_csv(os.path.join(outdir, "y_targets.csv"), index=False)


def build_sample_metadata(df: pd.DataFrame, profile: ModelProfile) -> pd.DataFrame:
    """Per-row metadata for supervised dataset generation (no relabel)."""
    meta = pd.DataFrame({"row_id": np.arange(len(df), dtype=np.int64), "profile": profile.name})
    for col in BIO_COLS + KPI_COLS + TARGET_COLS:
        meta[col] = df[col].values
    return meta


def build_target_matching_metadata(profile: ModelProfile) -> dict:
    """Document how simulated KPIs map to controller targets for this profile."""
    return {
        "profile": profile.name,
        "feature_columns": list(BIO_COLS + KPI_COLS),
        "target_columns": list(TARGET_COLS),
        "matching_rule": (
            "Each row simulates the ODE forward model with bio parameters (BIO_COLS) and "
            "controller settings u_max + Tthr_1..5 (TARGET_COLS). KPI columns P_AUC and "
            "LR1-LR5 are simulation outcomes used as X features; y_targets are the controller "
            "settings that produced those outcomes."
        ),
        **profile_provenance(profile),
    }


def save_dataset_artifacts(df: pd.DataFrame, profile: ModelProfile, outdir: str, n_bio: int) -> None:
    """Write supervised CSVs plus manifest / metadata for dataset generation."""
    write_feature_target_csv(df, outdir)
    sample_metadata_df = build_sample_metadata(df, profile)
    sample_metadata_path = os.path.join(outdir, "sample_metadata.csv")
    sample_metadata_df.to_csv(sample_metadata_path, index=False)

    target_matching = build_target_matching_metadata(profile)
    target_matching_path = os.path.join(outdir, "target_matching_metadata.json")
    write_json_manifest(outdir, "target_matching_metadata.json", target_matching)

    manifest = {
        "mode": "generate_dataset",
        "profile": profile.name,
        "n_bio": int(n_bio),
        "dataset_shape": [int(df.shape[0]), int(df.shape[1])],
        "output_files": {
            "wound_csv": "WOUND.csv",
            "x_features_csv": "X_features.csv",
            "y_targets_csv": "y_targets.csv",
            "sample_metadata_csv": "sample_metadata.csv",
            "target_matching_metadata_json": "target_matching_metadata.json",
        },
        "relabel_summary": profile_provenance(profile),
    }
    write_json_manifest(outdir, "ode_simulation_manifest.json", manifest)

    print("Saved X_features.csv and y_targets.csv")
    print(f"Saved {sample_metadata_path}")
    print(f"Saved {target_matching_path}")
    print("Saved ode_simulation_manifest.json")


def y_to_controller(y_pred: np.ndarray, columns: Optional[List[str]] = None) -> Tuple[float, np.ndarray]:
    """Return (u_max, T_thr[5]) from either column-labeled or original-order predictions."""
    arr = np.asarray(y_pred, dtype=float).reshape(-1)
    if len(arr) != 6:
        raise ValueError("Expected six control targets.")
    if columns is not None and set(TARGET_COLS).issubset(set(columns)):
        series = pd.Series(arr, index=columns)
        u = float(series["u_max"])
        T = series[[f"Tthr_{i}" for i in range(1, 6)]].values.astype(float)
    else:
        # Original uploaded-code order.
        u = float(arr[0])
        T = arr[1:6].astype(float)
    return float(np.clip(u, 0.0, None)), np.clip(T, 1.0, None)


def train_dcn(X_train, y_train_log, X_val, y_val_log, epochs: int = 250, batch_size: int = 256):
    try:
        import tensorflow as tf
        from tensorflow.keras import Input, Model
        from tensorflow.keras.layers import Dense, Dropout, concatenate, Layer, LayerNormalization, Activation
        from tensorflow.keras.optimizers import Adam
        from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
    except Exception as exc:
        raise ImportError(
            "TensorFlow is required for the DCN component of the manuscript SRL model. "
            "Install it with: pip install tensorflow"
        ) from exc

    class CrossLayerV2(Layer):
        def __init__(self, rank=8, **kwargs):
            super().__init__(**kwargs)
            self.rank = rank

        def build(self, input_shape):
            dim = int(input_shape[0][-1])
            self.W = self.add_weight(name="W", shape=(dim, self.rank), initializer="glorot_uniform", trainable=True)
            self.v = self.add_weight(name="v", shape=(self.rank, 1), initializer="glorot_uniform", trainable=True)
            self.b = self.add_weight(name="b", shape=(dim,), initializer="zeros", trainable=True)
            self.ln = LayerNormalization()

        def call(self, inputs):
            x0, xl = inputs
            x_proj = tf.matmul(xl, self.W)
            x_proj = tf.matmul(x_proj, self.v)
            return self.ln(tf.multiply(x_proj, x0) + self.b + xl)

    def build_dcn(input_dim, output_dim):
        x0 = Input(shape=(input_dim,), name="features")
        xl = x0
        for _ in range(5):
            xl = CrossLayerV2(rank=8)([x0, xl])
        xd = x0
        for units in (128, 64):
            xd = Dense(units)(xd)
            xd = LayerNormalization()(xd)
            xd = Activation("swish")(xd)
            xd = Dropout(0.2)(xd)
        merged = concatenate([xl, xd])
        out = Dense(output_dim, activation=None, name="output")(merged)
        return Model(x0, out)

    tf.random.set_seed(42)
    model = build_dcn(X_train.shape[1], y_train_log.shape[1])
    model.compile(optimizer=Adam(1e-3), loss="mse")
    model.fit(
        X_train,
        y_train_log,
        validation_data=(X_val, y_val_log),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[
            EarlyStopping("val_loss", patience=20, restore_best_weights=True, verbose=1),
            ReduceLROnPlateau("val_loss", factor=0.5, patience=10, verbose=1),
        ],
        verbose=0,
    )
    return model


def train_compare(profile: ModelProfile, x_csv: str, y_csv: str, baseline: str, sample_index: int, outdir: str) -> None:
    try:
        from xgboost import XGBRegressor
        from lightgbm import LGBMRegressor
    except Exception as exc:
        raise ImportError("xgboost and lightgbm are required: pip install xgboost lightgbm") from exc

    X_df = pd.read_csv(x_csv).dropna()
    y_df = pd.read_csv(y_csv).loc[X_df.index].dropna()
    X_df = X_df.loc[y_df.index]
    if set(TARGET_COLS).issubset(y_df.columns):
        y_df = y_df[TARGET_COLS]
    if y_df.shape[1] != 6:
        raise ValueError("y_targets.csv must have six columns: u_max and Tthr_1..Tthr_5.")

    X = X_df.values
    y = y_df.values
    y_log = np.log1p(np.clip(y, 0.0, None))

    X_train_raw, X_val_raw, y_train_log, y_val_log, y_train, y_val = train_test_split(
        X, y_log, y, test_size=0.15, random_state=42
    )

    scaler = StandardScaler().fit(X_train_raw)
    X_train = scaler.transform(X_train_raw)
    X_val = scaler.transform(X_val_raw)

    baseline = baseline.upper()
    if baseline == "GBDT":
        baseline_model = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100, random_state=42))
        baseline_model.fit(X_train, y_train_log)
        pred_base_log = baseline_model.predict(X_val)
        baseline_name = "GBDT"
    elif baseline == "XGBOOST":
        xgb_base = XGBRegressor(
            objective="reg:squarederror",
            n_estimators=300,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric="rmse",
            random_state=42,
            n_jobs=-1,
        )
        baseline_model = MultiOutputRegressor(xgb_base)
        baseline_model.fit(X_train, y_train_log)
        pred_base_log = baseline_model.predict(X_val)
        baseline_name = "XGBoost"
    else:
        raise ValueError("baseline must be 'GBDT' or 'XGBoost'.")

    # XGBoost base learner for SRL.
    xgb_models = []
    for i in range(y_train_log.shape[1]):
        model = XGBRegressor(
            objective="reg:squarederror",
            n_estimators=300,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric="rmse",
            random_state=42,
            n_jobs=-1,
        )
        model.fit(X_train, y_train_log[:, i])
        xgb_models.append(model)
    pred_train_xgb = np.column_stack([m.predict(X_train) for m in xgb_models])
    pred_val_xgb = np.column_stack([m.predict(X_val) for m in xgb_models])

    # DCN base learner for SRL.
    dcn = train_dcn(X_train, y_train_log, X_val, y_val_log)
    pred_train_dcn = dcn.predict(X_train, verbose=0)
    pred_val_dcn = dcn.predict(X_val, verbose=0)

    # Stacked residual logic in log target space.
    init_train = 0.5 * (pred_train_dcn + pred_train_xgb)
    init_val = 0.5 * (pred_val_dcn + pred_val_xgb)
    resid_train = y_train_log - init_train
    meta_train = np.hstack([pred_train_dcn, pred_train_xgb])
    meta_val = np.hstack([pred_val_dcn, pred_val_xgb])

    res_base = LGBMRegressor(
        n_estimators=500,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        n_jobs=-1,
        verbosity=-1,
        device_type="gpu",
    )
    res_model = MultiOutputRegressor(res_base)
    try:
        res_model.fit(meta_train, resid_train)
    except Exception as exc:
        import warnings

        warnings.warn(f"LightGBM GPU fit failed ({exc}); retrying on CPU.", stacklevel=2)
        res_base.set_params(device_type="cpu")
        res_model = MultiOutputRegressor(res_base)
        res_model.fit(meta_train, resid_train)
    resid_pred_val = res_model.predict(meta_val)
    final_pred_log = init_val + resid_pred_val

    true_val = np.expm1(y_val_log)
    pred_srl = np.expm1(final_pred_log)
    pred_base = np.expm1(pred_base_log)

    r2_srl_each = [r2_score(true_val[:, i], pred_srl[:, i]) for i in range(true_val.shape[1])]
    r2_base_each = [r2_score(true_val[:, i], pred_base[:, i]) for i in range(true_val.shape[1])]
    r2_df = pd.DataFrame({"target": list(y_df.columns), "SRL_R2": r2_srl_each, f"{baseline_name}_R2": r2_base_each})
    r2_df.loc[len(r2_df)] = ["mean", float(np.mean(r2_srl_each)), float(np.mean(r2_base_each))]
    r2_df.to_csv(os.path.join(outdir, "model_r2_summary.csv"), index=False)

    idx = int(sample_index)
    if idx < 0 or idx >= X_val_raw.shape[0]:
        raise IndexError("sample_index out of range for validation set.")
    bio = X_val_raw[idx, :25]
    B0 = bio[0:5]
    k_arr = bio[5:10]
    gamma_arr = bio[10:15]
    rho_arr = bio[15:20]
    mu_arr = bio[20:25]

    u_srl, T_srl = y_to_controller(pred_srl[idx], list(y_df.columns))
    u_base, T_base = y_to_controller(pred_base[idx], list(y_df.columns))
    res_srl = simulate_case(profile, B0, k_arr, gamma_arr, rho_arr, mu_arr, u_srl, T_srl)
    res_baseline = simulate_case(profile, B0, k_arr, gamma_arr, rho_arr, mu_arr, u_base, T_base)

    save_train_compare_trajectory_artifact(res_srl, outdir)
    pd.concat([metrics_dataframe("SRL", res_srl), metrics_dataframe(baseline_name, res_baseline)], ignore_index=True).to_csv(
        os.path.join(outdir, "reviewer_closed_loop_metrics.csv"), index=False
    )

    print("Saved model_r2_summary.csv")
    print("Saved reviewer_closed_loop_metrics.csv")


# ---------------------------------------------------------------------------
# Paper-figure legacy API (microbio_dataset / closed_loop_eval)
# Same post-processing as the former ode_simulator; integration uses simulate_case above.
# ---------------------------------------------------------------------------

PAPER_FIGURE_PROFILE = get_profile("paper_figure")
K_PATHOGEN = PAPER_FIGURE_PROFILE.K_pathogen
K_REP = PAPER_FIGURE_PROFILE.k_rep
B0_S_REP = PAPER_FIGURE_PROFILE.B0_rep
MU_REP = PAPER_FIGURE_PROFILE.mu_rep
GAMMA_S_REP = PAPER_FIGURE_PROFILE.gamma_s_rep
RHO_REP = PAPER_FIGURE_PROFILE.rho_rep
ALPHA = PAPER_FIGURE_PROFILE.alpha
BETA = PAPER_FIGURE_PROFILE.beta
P0_S_REP = float(PAPER_FIGURE_PROFILE.P0)


@dataclass
class LegacySimulationResult:
    times: np.ndarray
    B_total: np.ndarray
    B_S: np.ndarray
    B_R: np.ndarray
    P_S: np.ndarray
    P_R: np.ndarray
    C: np.ndarray
    dose_times: List[float]
    dose_count: int
    total_dosage: float
    P_AUC: float
    LR: np.ndarray
    LR_final: np.ndarray
    LR_terminal_median: np.ndarray
    LR_terminal_mean: np.ndarray
    pathogen_AUC: np.ndarray
    LR_auc: np.ndarray
    final_total_pathogen: float
    final_probiotic: float


def _legacy_metrics_from_trajectory(
    B0: np.ndarray,
    times: np.ndarray,
    B_total: np.ndarray,
    P_total: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    t_end = float(times[-1])
    terminal_mask = times >= (t_end - 12.0) - 1e-12
    B_terminal = B_total[terminal_mask]
    LR_final = np.log10(B0 / np.clip(B_total[-1], 1.0, None))
    LR_terminal_median = np.log10(B0 / np.clip(np.median(B_terminal, axis=0), 1.0, None))
    LR_terminal_mean = np.log10(B0 / np.clip(np.mean(B_terminal, axis=0), 1.0, None))
    pathogen_AUC = np.trapezoid(B_total, times, axis=0) / t_end
    LR_auc = np.log10(B0 / np.clip(pathogen_AUC, 1.0, None))
    return LR_final, LR_terminal_median, LR_terminal_mean, pathogen_AUC, LR_auc


def simulate_paper_case(
    B0: np.ndarray = B0_S_REP,
    k_arr: np.ndarray = K_REP,
    gamma_arr: np.ndarray = GAMMA_S_REP,
    rho_arr: np.ndarray = RHO_REP,
    mu_arr: np.ndarray = MU_REP,
    u_max: float = PAPER_FIGURE_PROFILE.u_max_rep,
    T_thr: np.ndarray = PAPER_FIGURE_PROFILE.T_thr_rep,
) -> LegacySimulationResult:
    """Legacy positional API for dataset generation and closed-loop evaluation."""
    raw = simulate_case(
        PAPER_FIGURE_PROFILE,
        B0,
        k_arr,
        gamma_arr,
        rho_arr,
        mu_arr,
        u_max,
        T_thr,
        return_history=True,
    )
    P_total = raw.P_total
    P_S = raw.P_S if raw.P_S is not None else np.zeros_like(P_total)
    P_R = raw.P_T if raw.P_T is not None else np.zeros_like(P_total)
    LR_final, LR_terminal_median, LR_terminal_mean, pathogen_AUC, LR_auc = _legacy_metrics_from_trajectory(
        np.asarray(B0, dtype=float),
        raw.times,
        raw.B_total,
        P_total,
    )
    return LegacySimulationResult(
        times=raw.times,
        B_total=raw.B_total,
        B_S=raw.B_S,
        B_R=raw.B_T,
        P_S=P_S,
        P_R=P_R,
        C=raw.C,
        dose_times=list(raw.dose_times),
        dose_count=int(raw.dose_count),
        total_dosage=float(raw.total_dosage),
        P_AUC=float(raw.P_AUC),
        LR=LR_terminal_median.copy(),
        LR_final=LR_final,
        LR_terminal_median=LR_terminal_median,
        LR_terminal_mean=LR_terminal_mean,
        pathogen_AUC=pathogen_AUC,
        LR_auc=LR_auc,
        final_total_pathogen=float(raw.B_total[-1].sum()),
        final_probiotic=float(P_total[-1]),
    )


def simulation_outcome_row(res: LegacySimulationResult) -> List[float]:
    return [
        res.dose_count,
        res.total_dosage,
        res.final_total_pathogen,
        res.final_probiotic,
        float(np.mean(res.LR_final)),
        float(np.min(res.LR_final)),
        *res.LR_final.tolist(),
        *res.LR_terminal_median.tolist(),
        *res.LR_terminal_mean.tolist(),
        *res.pathogen_AUC.tolist(),
        *res.LR_auc.tolist(),
    ]


def row_from_case(B0, k_arr, gamma_arr, rho_arr, mu_arr, u_max, T_thr) -> np.ndarray:
    res = simulate_paper_case(B0, k_arr, gamma_arr, rho_arr, mu_arr, u_max, T_thr)
    return np.concatenate(
        [B0, k_arr, gamma_arr, rho_arr, mu_arr, [u_max], T_thr, [res.P_AUC], res.LR, simulation_outcome_row(res)]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Review-ready wound control simulation and ML pipeline")
    parser.add_argument("--mode", choices=["representative", "generate_dataset", "train_compare"], default="representative")
    parser.add_argument(
        "--profile",
        default="paper_figure",
        choices=list(PROFILE_ALIASES),
        help="ODE parameter profile (default: paper_figure).",
    )
    parser.add_argument("--outdir", default=".")
    parser.add_argument("--n_bio", type=int, default=500, help="500 gives 220,000 rows under the default LHS grid.")
    parser.add_argument("--x_csv", default="X_features.csv")
    parser.add_argument("--y_csv", default="y_targets.csv")
    parser.add_argument("--baseline", default="GBDT", choices=["GBDT", "XGBoost"])
    parser.add_argument("--sample_index", type=int, default=0)
    args = parser.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    profile = get_profile(args.profile)

    if args.mode == "representative":
        res = simulate_case(profile)
        save_representative_artifacts(res, profile, args.outdir)
        print(f"profile={profile.name}, P_AUC={res.P_AUC:.6g}, LR={np.round(res.LR, 4)}, doses={res.dose_count}, total_dosage={res.total_dosage:.1f} ug/mL")

    elif args.mode == "generate_dataset":
        df = generate_rows(profile, n_bio=args.n_bio)
        wound_path = os.path.join(args.outdir, "WOUND.csv")
        df.to_csv(wound_path, index=False)
        save_dataset_artifacts(df, profile, args.outdir, n_bio=args.n_bio)
        print(f"Saved {wound_path}")
        print(f"Dataset shape: {df.shape}")

    elif args.mode == "train_compare":
        train_compare(profile, args.x_csv, args.y_csv, args.baseline, args.sample_index, args.outdir)


if __name__ == "__main__":
    main()
